[package]
name = "AccessControllerBridge"
license = "Apache-2.0"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
Hierarchies = { local = "../../hierarchies-move" }
TfComponents = { git = "https://github.com/iotaledger/product-core.git", subdir = "components_move", rev = "feat/tf-compoenents-dev" }

[addresses]
access_controller_bridge = "0x0"

[dev-dependencies]

[dev-addresses]
