[workspace]
members = ["htf", "examples"]
resolver = "2"


[workspace.package]
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
license = "Apache-2.0"
repository = "https://github.com/iotaledger/htf"


[workspace.dependencies]
serde = { version = "1.0", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = { version = "1.0", default-features = false }
strum = { version = "0.26", default-features = false, features = [
    "std",
    "derive",
] }
thiserror = { version = "1.0", default-features = false }
