[package]
name = "examples"
edition.workspace = true
authors.workspace = true

[dependencies]
iota-sdk.workspace = true
serde_json.workspace = true
tokio.workspace = true
anyhow.workspace = true
iota-keys.workspace = true
fastcrypto.workspace = true
iota.workspace = true
secret-storage.workspace = true
htf = { path = "../htf" }
jsonpath-rust.workspace = true
async-trait.workspace = true

[lib]
path = "utils.rs"

[[example]]
path = "01_create_federation.rs"
name = "01_create_federation"
